version: "3.3"

networks:
  nginx-router_default:
services:
  nginx:
      networks:
        - nginx-router_default
      build:
        context: ../arianoangelo/conf/nginx
        dockerfile: nginx.dockerfile
      image: nginx-router
      container_name: nginx_router
      restart: unless-stopped
      volumes:
        - ./volumes/web/media:/data/media
        - ./volumes/web/static:/data/static
      depends_on:
        - web
      ports:
        - "80:80"
        - "443:443"
  db:
    image: postgres
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    networks:
      - nginx-router_default
    environment:
      - POSTGRES_DB=arianoangelo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    build:
      context: ./conf/web
      dockerfile: Dockerfile
    container_name: arianoangelo-web
    environment:
      MODULE_NAME: arianoangelo.asgi
      VARIABLE_NAME: application
    command: run_server
    restart: unless-stopped
    networks:
      - nginx-router_default
    depends_on:
      - db
    volumes:
      - ./volumes/web:/app
    expose:
      - "80"

