# Generated by Django 2.2.4 on 2019-11-16 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insert the category name.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insira o nome', max_length=200)),
                ('text', models.TextField(help_text='Insira o Texto', max_length=500)),
                ('portfolio_image', models.ImageField(upload_to='portfolio-photos')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 16, 1, 5, 20, 177283, tzinfo=utc), verbose_name='Data de realização')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(help_text='Select the category', to='portfolio.Category')),
            ],
        ),
    ]
