# Generated by Django 2.2.4 on 2019-11-16 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(default=datetime.date(2019, 11, 16), verbose_name='Data de realização'),
        ),
    ]
