# Generated by Django 2.2.4 on 2019-11-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20191116_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(help_text='Type the name', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='text',
            field=models.TextField(help_text='Type the text', max_length=500),
        ),
    ]
