# Generated by Django 2.2.6 on 2019-11-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20191116_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=100),
        ),
    ]
