# Generated by Django 2.2.6 on 2019-11-17 02:23

from django.db import migrations, models
from random import randrange
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default=randrange(10), unique=False),
            preserve_default=False,
        ),
    ]
