# Generated by Django 3.0 on 2020-04-18 15:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20191117_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
