# Generated by Django 3.0.5 on 2020-04-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20200418_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Set a name for the image', max_length=200)),
                ('image', models.ImageField(upload_to='portfolio-photos')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='images',
            field=models.ManyToManyField(help_text='Select the images of this post', to='portfolio.Images'),
        ),
    ]
