# Generated by Django 3.0.5 on 2020-04-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200425_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
