# Generated by Django 3.0.5 on 2020-04-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20200425_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Select the images of this post', to='portfolio.Image'),
        ),
    ]
